function(e,s,r,gg){
var cOP=_n('view')
_r(cOP,'class',573,e,s,gg)
var oPP=_m('text',['bindtap',574,'class',1,'data-index',2],[],e,s,gg)
var lQP=_o(577,e,s,gg)
_(oPP,lQP)
_(cOP,oPP)
var aRP=_m('text',['bindtap',578,'class',1,'data-index',2],[],e,s,gg)
var tSP=_o(581,e,s,gg)
_(aRP,tSP)
_(cOP,aRP)
var eTP=_m('text',['bindtap',582,'class',1,'data-index',2],[],e,s,gg)
var bUP=_o(585,e,s,gg)
_(eTP,bUP)
_(cOP,eTP)
_(r,cOP)
var cLP=_v()
_(r,cLP)
if(_o(586,e,s,gg)){cLP.wxVkey=1
cLP.wxXCkey=1
var oVP=_n('view')
_r(oVP,'class',587,e,s,gg)
var xWP=_m('swiper',['autoplay',588,'class',1,'duration',2,'indicatorDots',3,'interval',4,'style',5],[],e,s,gg)
var oXP=_v()
_(xWP,oXP)
var fYP=function(h1P,cZP,o2P,gg){
var o4P=_n('swiper-item')
var l5P=_m('image',['bindtap',596,'class',1,'data-current',2,'mode',3,'src',4],[],h1P,cZP,gg)
_(o4P,l5P)
_(o2P,o4P)
return o2P
}
oXP.wxXCkey=2
_2(594,fYP,e,s,gg,oXP,'item','index','')
_(oVP,xWP)
var a6P=_n('view')
_r(a6P,'class',601,e,s,gg)
var t7P=_n('view')
_r(t7P,'class',602,e,s,gg)
var e8P=_n('text')
_r(e8P,'class',603,e,s,gg)
var b9P=_o(604,e,s,gg)
_(e8P,b9P)
_(t7P,e8P)
_(a6P,t7P)
var o0P=_n('view')
_r(o0P,'class',605,e,s,gg)
_(a6P,o0P)
var xAQ=_m('view',['bindtap',606,'class',1,'data-id',2],[],e,s,gg)
var oBQ=_n('image')
_r(oBQ,'src',609,e,s,gg)
_(xAQ,oBQ)
_(a6P,xAQ)
_(oVP,a6P)
var fCQ=_n('view')
_r(fCQ,'class',610,e,s,gg)
var cDQ=_n('text')
_r(cDQ,'class',611,e,s,gg)
var hEQ=_o(612,e,s,gg)
_(cDQ,hEQ)
_(fCQ,cDQ)
var oFQ=_n('text')
_r(oFQ,'class',613,e,s,gg)
var cGQ=_o(614,e,s,gg)
_(oFQ,cGQ)
_(fCQ,oFQ)
var oHQ=_n('text')
_r(oHQ,'class',615,e,s,gg)
var lIQ=_o(616,e,s,gg)
_(oHQ,lIQ)
_(fCQ,oHQ)
_(oVP,fCQ)
var aJQ=_n('view')
_r(aJQ,'class',617,e,s,gg)
var tKQ=_n('text')
var eLQ=_o(618,e,s,gg)
_(tKQ,eLQ)
_(aJQ,tKQ)
var bMQ=_n('text')
var oNQ=_o(619,e,s,gg)
_(bMQ,oNQ)
_(aJQ,bMQ)
var xOQ=_n('text')
var oPQ=_o(620,e,s,gg)
_(xOQ,oPQ)
_(aJQ,xOQ)
_(oVP,aJQ)
var fQQ=_n('text')
_r(fQQ,'class',621,e,s,gg)
var cRQ=_o(622,e,s,gg)
_(fQQ,cRQ)
_(oVP,fQQ)
var hSQ=_n('view')
_r(hSQ,'class',623,e,s,gg)
_(oVP,hSQ)
var oTQ=_v()
_(oVP,oTQ)
var cUQ=function(lWQ,oVQ,aXQ,gg){
var eZQ=_n('view')
_r(eZQ,'class',626,lWQ,oVQ,gg)
var b1Q=_n('text')
_r(b1Q,'class',627,lWQ,oVQ,gg)
var o2Q=_o(628,lWQ,oVQ,gg)
_(b1Q,o2Q)
_(eZQ,b1Q)
var x3Q=_n('view')
_r(x3Q,'class',629,lWQ,oVQ,gg)
var o4Q=_v()
_(x3Q,o4Q)
var f5Q=function(h7Q,c6Q,o8Q,gg){
var o0Q=_m('text',['bindtap',631,'class',1,'data-index',2,'data-pos',3],[],h7Q,c6Q,gg)
var lAR=_o(635,h7Q,c6Q,gg)
_(o0Q,lAR)
_(o8Q,o0Q)
return o8Q
}
o4Q.wxXCkey=2
_2(630,f5Q,lWQ,oVQ,gg,o4Q,'item','index','')
_(eZQ,x3Q)
_(aXQ,eZQ)
return aXQ
}
oTQ.wxXCkey=2
_2(625,cUQ,e,s,gg,oTQ,'item','pos','')
var aBR=_n('view')
_r(aBR,'class',636,e,s,gg)
_(oVP,aBR)
var tCR=_n('text')
_r(tCR,'class',637,e,s,gg)
var eDR=_o(638,e,s,gg)
_(tCR,eDR)
_(oVP,tCR)
var bER=_n('view')
_r(bER,'class',639,e,s,gg)
_(oVP,bER)
var oFR=_n('view')
var xGR=_n('view')
_r(xGR,'class',640,e,s,gg)
var oHR=_m('text',['bindtap',641,'class',1,'data-index',2],[],e,s,gg)
var fIR=_o(644,e,s,gg)
_(oHR,fIR)
_(xGR,oHR)
var cJR=_m('input',['bindchange',645,'data-index',1,'type',2,'value',3],[],e,s,gg)
_(xGR,cJR)
var hKR=_m('text',['bindtap',649,'class',1,'data-index',2],[],e,s,gg)
var oLR=_o(652,e,s,gg)
_(hKR,oLR)
_(xGR,hKR)
_(oFR,xGR)
_(oVP,oFR)
var cMR=_n('view')
_r(cMR,'style',653,e,s,gg)
_(oVP,cMR)
var oNR=_n('view')
_r(oNR,'class',654,e,s,gg)
var lOR=_v()
_(oNR,lOR)
var aPR=function(eRR,tQR,bSR,gg){
var xUR=_m('image',['mode',657,'src',1],[],eRR,tQR,gg)
_(bSR,xUR)
return bSR
}
lOR.wxXCkey=2
_2(655,aPR,e,s,gg,lOR,'item','index','')
_(oVP,oNR)
_(cLP,oVP)
}
var hMP=_v()
_(r,hMP)
if(_o(659,e,s,gg)){hMP.wxVkey=1
hMP.wxXCkey=1
var oVR=_n('view')
_r(oVR,'class',660,e,s,gg)
var fWR=e_[x[10]].i
var cXR=_n('text')
_r(cXR,'class',661,e,s,gg)
var hYR=_o(662,e,s,gg)
_(cXR,hYR)
_(oVR,cXR)
var oZR=_n('view')
_r(oZR,'class',663,e,s,gg)
_(oVR,oZR)
var c1R=_v()
_(oVR,c1R)
var o2R=function(a4R,l3R,t5R,gg){
var b7R=_n('text')
_r(b7R,'class',665,a4R,l3R,gg)
var o8R=_o(666,a4R,l3R,gg)
_(b7R,o8R)
_(t5R,b7R)
return t5R
}
c1R.wxXCkey=2
_2(664,o2R,e,s,gg,c1R,'item','index','')
_ai(fWR,x[5],e_,x[10],91,4)
var x9R=_m('view',['class',667,'style',1],[],e,s,gg)
var o0R=_v()
_(x9R,o0R)
var fAS=_o(670,e,s,gg)
var cBS=_gd(x[10],fAS,e_,d_)
if(cBS){
var hCS=_1(669,e,s,gg)
var cur_globalf=gg.f
gg.valuekey.push(669)
cBS(hCS,hCS,o0R,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(fAS,x[10],93,16)
_(oVR,x9R)
fWR.pop()
_(hMP,oVR)
}
var oNP=_v()
_(r,oNP)
if(_o(671,e,s,gg)){oNP.wxVkey=1
oNP.wxXCkey=1
var oDS=_n('view')
_r(oDS,'class',672,e,s,gg)
var cES=_n('view')
_r(cES,'class',673,e,s,gg)
var oFS=_v()
_(cES,oFS)
var lGS=function(tIS,aHS,eJS,gg){
var oLS=_n('view')
_r(oLS,'class',676,tIS,aHS,gg)
var xMS=_n('view')
_r(xMS,'class',677,tIS,aHS,gg)
var oNS=_m('image',['class',678,'mode',1,'src',2],[],tIS,aHS,gg)
_(xMS,oNS)
var fOS=_n('text')
_r(fOS,'class',681,tIS,aHS,gg)
var cPS=_o(682,tIS,aHS,gg)
_(fOS,cPS)
_(xMS,fOS)
_(oLS,xMS)
var hQS=_n('view')
_r(hQS,'class',683,tIS,aHS,gg)
var oRS=_n('text')
_r(oRS,'class',684,tIS,aHS,gg)
var cSS=_o(685,tIS,aHS,gg)
_(oRS,cSS)
_(hQS,oRS)
var oTS=_n('view')
_r(oTS,'calss',686,tIS,aHS,gg)
var lUS=_v()
_(oTS,lUS)
if(_o(687,tIS,aHS,gg)){lUS.wxVkey=1
lUS.wxXCkey=1
var aVS=_m('image',['class',688,'src',1],[],tIS,aHS,gg)
_(lUS,aVS)
}
else if(_o(690,tIS,aHS,gg)){lUS.wxVkey=2
var tWS=_m('image',['class',691,'src',1],[],tIS,aHS,gg)
_(lUS,tWS)
}
else if(_o(693,tIS,aHS,gg)){lUS.wxVkey=3
var eXS=_m('image',['class',694,'src',1],[],tIS,aHS,gg)
_(lUS,eXS)
}
else if(_o(696,tIS,aHS,gg)){lUS.wxVkey=4
var bYS=_m('image',['class',697,'src',1],[],tIS,aHS,gg)
_(lUS,bYS)
}
else if(_o(699,tIS,aHS,gg)){lUS.wxVkey=5
var oZS=_m('image',['class',700,'src',1],[],tIS,aHS,gg)
_(lUS,oZS)
}
else if(_o(702,tIS,aHS,gg)){lUS.wxVkey=6
var x1S=_m('image',['class',703,'src',1],[],tIS,aHS,gg)
_(lUS,x1S)
}
var o2S=_n('text')
_r(o2S,'class',705,tIS,aHS,gg)
var f3S=_o(706,tIS,aHS,gg)
_(o2S,f3S)
_(oTS,o2S)
_(hQS,oTS)
_(oLS,hQS)
var c4S=_n('view')
_r(c4S,'class',707,tIS,aHS,gg)
_(oLS,c4S)
_(eJS,oLS)
return eJS
}
oFS.wxXCkey=2
_2(674,lGS,e,s,gg,oFS,'item','index','index')
_(oDS,cES)
_(oNP,oDS)
}
var h5S=_n('view')
_r(h5S,'class',708,e,s,gg)
var o6S=_m('button',['bindtap',709,'class',1],[],e,s,gg)
var c7S=_o(711,e,s,gg)
_(o6S,c7S)
_(h5S,o6S)
var o8S=_m('button',['bindtap',712,'class',1],[],e,s,gg)
var l9S=_o(714,e,s,gg)
_(o8S,l9S)
_(h5S,o8S)
_(r,h5S)
return r
}