var e = "https://userapi.hiweixiu.com/";

module.exports = {
    version: "0.9.3.0",
    clientType: "120",
    jwtKey: "mipvssjx7sqebrszg2pjprdf9syseecu",
    recycleKey: "5b46fc265b786a1b5edcf59d6ee06786",
    storageKeys: {
        timeDifference: "kTimeDifference",
        currentDevice: "kCurrentDevice",
        currentUser: "kCurrentUser",
        selectedAddress: "kSelectedAddress",
        selectedDevice: "kSelectedDevice",
        selectedPlan: "kSelectedPlan"
    },
    apiList: {
        nowTime: e + "index-weapp/get-now-time",
        memoryUpCreateOrder: e + "order-weapp/create-order-special-form",
        cityListByProvince: e + "region-weapp/get-cities-by-province",
        provinceList: e + "region-weapp/province-list",
        memoryPriceList: e + "index-weapp/get-memory-price-list",
        faultListByMouldId: e + "fault-weapp/get-faults-by-mouldid",
        hotFix: e + "index-weapp/get-hot-fix",
        banner: e + "fault-weapp/return-banner?type=weapp",
        quickCreatOrder: e + "order-weapp/create-handy-order",
        districtList: e + "region-weapp/get-districts-by-city",
        visitPairCityList: e + "region-weapp/city-list",
        reserveTime: e + "order/get-reserve-time",
        faultList: e + "fault-weapp/mould-fault",
        deviceInfo: e + "moiblemould-weapp/getids",
        getColors: e + "colors/get-colors",
        warrantyOption: e + "moiblemould/get-warranty-option-by-mid",
        repairMsg: e + "repairprice-weapp/get-repair-msg",
        faultComment: e + "comment/new-get-y-comments",
        sendCode: e + "hiuser/verificate-code",
        doLogin: e + "hiuser-weapp/login",
        addressList: e + "user-weapp/look-address",
        addAddress: e + "user-weapp/add-address",
        cityInfo: e + "region/is-open-city",
        createOrder: e + "order/new-create-order",
        orderDetail: e + "order/detail",
        workerLocation: e + "order/get-engineer-position",
        brandList: e + "moiblemould-weapp/get-brand-list?type=1",
        mouldList: e + "moiblemould-weapp/get-mould-list-by-bid",
        orderList: e + "order/listnew",
        editName: e + "user/edit-name",
        editBirthday: e + "user/edit-birthday",
        logout: e + "hiuser/logout",
        configList: e + "index-weapp/config-list",
        getHotRecycle: e + "shr-weapp/get-hot-device",
        getRecycleBrand: e + "shr-weapp/get-brand-list",
        getRecycleMould: e + "shr-weapp/get-mould-list-by-bid",
        createRecycleOrder: e + "shr-weapp/create-order2",
        getRecycleDetail: e + "shr-weapp/get-shr-order-info-by-id",
        getRecycleFault: e + "shr-weapp/get-attr-fault-list",
        getAppraisePrice: e + "shr-weapp/get-appraise-result",
        getRecycleCart: e + "cart-weapp/get-cart",
        recycleCartDel: e + "cart-weapp/delete-cart",
        showCartDetail: e + "cart-weapp/get-information",
        addToCart: e + "cart-weapp/add-cart",
        getCartNum: e + "cart-weapp/get-cart-number",
        getRepairCoupon: e + "order/new-get-coupon",
        addRepairCoupon: e + "user/add-coupon",
        myCouponList: e + "user/new-coupon-list",
        makeCall: e + "order-weapp/make-call",
        getActiveUserinfo: e + "order-weapp/get-activity-user-info",
        immediateUseCoupon: e + "order-weapp/immediate-use-coupon",
        storeList: e + "region-weapp/get-store-list",
        listBox: e + "index-weapp/get-list-box"
    },
    apiCode: {
        success: 200,
        fail: 403,
        unauthorized: 401
    },
    strings: {
        requestFail: "请求失败"
    }
};