function(e,s,r,gg){
var hYR=e_[x[15]].i
_ai(hYR,x[5],e_,x[15],3,2)
_ai(hYR,x[16],e_,x[15],4,2)
_ai(hYR,x[17],e_,x[15],5,2)
var oZR=_n('view')
_r(oZR,'class',582,e,s,gg)
var c1R=_n('view')
_r(c1R,'class',583,e,s,gg)
var o2R=_m('swiper',['autoplay',584,'circular',1,'duration',2,'indicatorActiveColor',3,'indicatorDots',4,'interval',5],[],e,s,gg)
var l3R=_v()
_(o2R,l3R)
var a4R=function(e6R,t5R,b7R,gg){
var x9R=_n('swiper-item')
var o0R=_m('image',['mode',592,'src',1],[],e6R,t5R,gg)
_(x9R,o0R)
_(b7R,x9R)
return b7R
}
l3R.wxXCkey=2
_2(590,a4R,e,s,gg,l3R,'item','index','')
_(c1R,o2R)
_(oZR,c1R)
var fAS=_n('view')
_r(fAS,'class',594,e,s,gg)
var cBS=_n('view')
_r(cBS,'class',595,e,s,gg)
var hCS=_n('view')
_r(hCS,'class',596,e,s,gg)
var oDS=_m('image',['mode',597,'src',1],[],e,s,gg)
_(hCS,oDS)
_(cBS,hCS)
var cES=_n('view')
_r(cES,'class',599,e,s,gg)
var oFS=_n('view')
_r(oFS,'class',600,e,s,gg)
var lGS=_n('view')
var aHS=_o(601,e,s,gg)
_(lGS,aHS)
_(oFS,lGS)
_(cES,oFS)
var tIS=_n('view')
_r(tIS,'class',602,e,s,gg)
var eJS=_o(603,e,s,gg)
_(tIS,eJS)
_(cES,tIS)
_(cBS,cES)
_(fAS,cBS)
var bKS=_n('view')
_r(bKS,'class',604,e,s,gg)
var oLS=_m('view',['bindtap',605,'class',1],[],e,s,gg)
var xMS=_n('view')
_r(xMS,'class',607,e,s,gg)
var oNS=_n('text')
_r(oNS,'style',608,e,s,gg)
var fOS=_o(609,e,s,gg)
_(oNS,fOS)
_(xMS,oNS)
var cPS=_n('text')
_r(cPS,'style',610,e,s,gg)
var hQS=_o(611,e,s,gg)
_(cPS,hQS)
_(xMS,cPS)
_(oLS,xMS)
var oRS=_n('view')
_r(oRS,'class',612,e,s,gg)
var cSS=_o(613,e,s,gg)
_(oRS,cSS)
_(oLS,oRS)
_(bKS,oLS)
var oTS=_m('view',['bindtap',614,'class',1],[],e,s,gg)
var lUS=_n('view')
_r(lUS,'class',616,e,s,gg)
var aVS=_n('text')
_r(aVS,'style',617,e,s,gg)
var tWS=_o(618,e,s,gg)
_(aVS,tWS)
_(lUS,aVS)
var eXS=_n('text')
_r(eXS,'style',619,e,s,gg)
var bYS=_o(620,e,s,gg)
_(eXS,bYS)
_(lUS,eXS)
_(oTS,lUS)
var oZS=_n('view')
_r(oZS,'class',621,e,s,gg)
var x1S=_n('text')
var o2S=_o(622,e,s,gg)
_(x1S,o2S)
_(oZS,x1S)
_(oTS,oZS)
_(bKS,oTS)
_(fAS,bKS)
var f3S=_n('view')
_r(f3S,'class',623,e,s,gg)
var c4S=_v()
_(f3S,c4S)
if(_o(624,e,s,gg)){c4S.wxVkey=1
c4S.wxXCkey=1
var h5S=_n('text')
var o6S=_o(625,e,s,gg)
_(h5S,o6S)
_(c4S,h5S)
}
var c7S=_n('text')
var o8S=_o(626,e,s,gg)
_(c7S,o8S)
_(f3S,c7S)
_(fAS,f3S)
var l9S=_n('view')
_r(l9S,'class',627,e,s,gg)
var a0S=_n('view')
_r(a0S,'class',628,e,s,gg)
var tAT=_n('image')
_r(tAT,'src',629,e,s,gg)
_(a0S,tAT)
_(l9S,a0S)
var eBT=_n('view')
_r(eBT,'class',630,e,s,gg)
var bCT=_n('view')
var oDT=_o(631,e,s,gg)
_(bCT,oDT)
_(eBT,bCT)
_(l9S,eBT)
_(fAS,l9S)
var xET=_m('view',['bindtap',632,'class',1],[],e,s,gg)
var oFT=_o(634,e,s,gg)
_(xET,oFT)
_(fAS,xET)
var fGT=_n('view')
_r(fGT,'class',635,e,s,gg)
var cKT=_n('view')
_r(cKT,'class',636,e,s,gg)
var oLT=_v()
_(cKT,oLT)
var lMT=function(tOT,aNT,ePT,gg){
var oRT=_m('view',['bindtap',639,'class',1,'data-index',2],[],tOT,aNT,gg)
var xST=_o(642,tOT,aNT,gg)
_(oRT,xST)
_(ePT,oRT)
return ePT
}
oLT.wxXCkey=2
_2(637,lMT,e,s,gg,oLT,'item','index','')
_(fGT,cKT)
var cHT=_v()
_(fGT,cHT)
if(_o(643,e,s,gg)){cHT.wxVkey=1
cHT.wxXCkey=1
var oTT=_n('view')
_r(oTT,'class',644,e,s,gg)
var fUT=_n('view')
_r(fUT,'class',645,e,s,gg)
var cVT=_n('view')
var hWT=_o(646,e,s,gg)
_(cVT,hWT)
_(fUT,cVT)
var oXT=_m('view',['bindtap',647,'style',1],[],e,s,gg)
var cYT=_v()
_(oXT,cYT)
if(_o(649,e,s,gg)){cYT.wxVkey=1
cYT.wxXCkey=1
var oZT=_n('text')
var l1T=_o(650,e,s,gg)
_(oZT,l1T)
_(cYT,oZT)
}
else{cYT.wxVkey=2
var a2T=_n('text')
var t3T=_o(651,e,s,gg)
_(a2T,t3T)
_(cYT,a2T)
}
_(fUT,oXT)
_(oTT,fUT)
var e4T=_m('view',['class',652,'style',1],[],e,s,gg)
var b5T=_v()
_(e4T,b5T)
var o6T=_o(655,e,s,gg)
var x7T=_gd(x[15],o6T,e_,d_)
if(x7T){
var o8T=_1(654,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(654)
x7T(o8T,o8T,b5T,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(o6T,x[15],83,24)
_(oTT,e4T)
_(cHT,oTT)
}
var hIT=_v()
_(fGT,hIT)
if(_o(656,e,s,gg)){hIT.wxVkey=1
hIT.wxXCkey=1
var f9T=_n('view')
_r(f9T,'class',657,e,s,gg)
var c0T=_v()
_(f9T,c0T)
if(_o(658,e,s,gg)){c0T.wxVkey=1
c0T.wxXCkey=1
var hAU=_n('view')
_r(hAU,'class',659,e,s,gg)
var oBU=_n('view')
_r(oBU,'class',660,e,s,gg)
var cCU=_n('view')
var oDU=_o(661,e,s,gg)
_(cCU,oDU)
_(oBU,cCU)
var lEU=_m('view',['bindtap',662,'style',1],[],e,s,gg)
var aFU=_n('text')
var tGU=_o(664,e,s,gg)
_(aFU,tGU)
_(lEU,aFU)
_(oBU,lEU)
_(hAU,oBU)
var eHU=_v()
_(hAU,eHU)
var bIU=_o(666,e,s,gg)
var oJU=_gd(x[15],bIU,e_,d_)
if(oJU){
var xKU=_1(665,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(665)
oJU(xKU,xKU,eHU,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(bIU,x[15],95,24)
_(c0T,hAU)
}
var oLU=_v()
_(f9T,oLU)
var fMU=_o(668,e,s,gg)
var cNU=_gd(x[15],fMU,e_,d_)
if(cNU){
var hOU=_1(667,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(667)
cNU(hOU,hOU,oLU,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(fMU,x[15],97,22)
_(hIT,f9T)
}
var oJT=_v()
_(fGT,oJT)
if(_o(669,e,s,gg)){oJT.wxVkey=1
oJT.wxXCkey=1
var oPU=_n('view')
_r(oPU,'class',670,e,s,gg)
var oRU=_n('view')
_r(oRU,'class',671,e,s,gg)
var lSU=_n('view')
_r(lSU,'class',672,e,s,gg)
var aTU=_v()
_(lSU,aTU)
if(_o(673,e,s,gg)){aTU.wxVkey=1
aTU.wxXCkey=1
var tUU=_n('text')
var eVU=_o(674,e,s,gg)
_(tUU,eVU)
_(aTU,tUU)
}
else{aTU.wxVkey=2
var bWU=_n('text')
var oXU=_o(675,e,s,gg)
_(bWU,oXU)
_(aTU,bWU)
}
_(oRU,lSU)
var xYU=_n('view')
_r(xYU,'class',676,e,s,gg)
_(oRU,xYU)
_(oPU,oRU)
var cQU=_v()
_(oPU,cQU)
if(_o(677,e,s,gg)){cQU.wxVkey=1
cQU.wxXCkey=1
var oZU=_n('view')
_r(oZU,'class',678,e,s,gg)
var f1U=_v()
_(oZU,f1U)
var c2U=_o(680,e,s,gg)
var h3U=_gd(x[15],c2U,e_,d_)
if(h3U){
var o4U=_1(679,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(679)
h3U(o4U,o4U,f1U,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(c2U,x[15],109,24)
_(cQU,oZU)
}
_(oJT,oPU)
}
_(fAS,fGT)
_(oZR,fAS)
var c5U=_n('view')
_r(c5U,'class',681,e,s,gg)
var o6U=_m('view',['bindtap',682,'class',1,'data-uid',2],[],e,s,gg)
var l7U=_n('view')
_r(l7U,'class',685,e,s,gg)
var a8U=_n('image')
_r(a8U,'src',686,e,s,gg)
_(l7U,a8U)
_(o6U,l7U)
var t9U=_n('view')
_r(t9U,'class',687,e,s,gg)
var e0U=_o(688,e,s,gg)
_(t9U,e0U)
_(o6U,t9U)
_(c5U,o6U)
var bAV=_v()
_(c5U,bAV)
var oBV=function(oDV,xCV,fEV,gg){
var hGV=_m('view',['bindtap',691,'class',1],[],oDV,xCV,gg)
var oHV=_n('view')
_r(oHV,'class',693,oDV,xCV,gg)
var cIV=_n('image')
_r(cIV,'src',694,oDV,xCV,gg)
_(oHV,cIV)
_(hGV,oHV)
var oJV=_n('view')
_r(oJV,'class',695,oDV,xCV,gg)
var lKV=_o(696,oDV,xCV,gg)
_(oJV,lKV)
_(hGV,oJV)
_(fEV,hGV)
return fEV
}
bAV.wxXCkey=2
_2(689,oBV,e,s,gg,bAV,'item','index','')
_(oZR,c5U)
var aLV=_m('view',['class',697,'hidden',1],[],e,s,gg)
var eNV=_n('view')
_r(eNV,'class',699,e,s,gg)
var bOV=_m('image',['bindtap',700,'src',1],[],e,s,gg)
_(eNV,bOV)
_(aLV,eNV)
var oPV=_n('view')
_r(oPV,'class',702,e,s,gg)
var xQV=_m('image',['bindtap',703,'src',1],[],e,s,gg)
_(oPV,xQV)
_(aLV,oPV)
var tMV=_v()
_(aLV,tMV)
if(_o(705,e,s,gg)){tMV.wxVkey=1
tMV.wxXCkey=1
var oRV=_n('view')
_r(oRV,'class',706,e,s,gg)
var fSV=_o(707,e,s,gg)
_(oRV,fSV)
_(tMV,oRV)
}
_(oZR,aLV)
var cTV=_n('view')
_r(cTV,'class',708,e,s,gg)
var hUV=_v()
_(cTV,hUV)
var oVV=_o(710,e,s,gg)
var cWV=_gd(x[15],oVV,e_,d_)
if(cWV){
var oXV=_1(709,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(709)
cWV(oXV,oXV,hUV,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(oVV,x[15],142,18)
_(oZR,cTV)
var lYV=_v()
_(oZR,lYV)
var aZV=_o(712,e,s,gg)
var t1V=_gd(x[15],aZV,e_,d_)
if(t1V){
var e2V=_1(711,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(711)
t1V(e2V,e2V,lYV,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(aZV,x[15],145,16)
_(r,oZR)
hYR.pop()
hYR.pop()
hYR.pop()
return r
}