function(e,s,r,gg){
var b1C=e_[x[4]].i
_ai(b1C,x[5],e_,x[4],3,2)
var o2C=_n('view')
_r(o2C,'class',91,e,s,gg)
var x3C=_v()
_(o2C,x3C)
if(_o(92,e,s,gg)){x3C.wxVkey=1
x3C.wxXCkey=1
var c6C=_n('view')
_r(c6C,'class',93,e,s,gg)
var h7C=_m('swiper',['autoplay',94,'circular',1,'duration',2,'indicatorActiveColor',3,'indicatorDots',4,'interval',5],[],e,s,gg)
var o8C=_v()
_(h7C,o8C)
var c9C=function(lAD,o0C,aBD,gg){
var eDD=_n('swiper-item')
var bED=_m('image',['mode',102,'src',1],[],lAD,o0C,gg)
_(eDD,bED)
_(aBD,eDD)
return aBD
}
o8C.wxXCkey=2
_2(100,c9C,e,s,gg,o8C,'item','index','')
_(c6C,h7C)
_(x3C,c6C)
}
var oFD=_n('view')
_r(oFD,'class',104,e,s,gg)
var xGD=_n('view')
_r(xGD,'class',105,e,s,gg)
var oHD=_n('view')
var fID=_o(106,e,s,gg)
_(oHD,fID)
_(xGD,oHD)
var cJD=_n('view')
_r(cJD,'style',107,e,s,gg)
var hKD=_o(108,e,s,gg)
_(cJD,hKD)
_(xGD,cJD)
_(oFD,xGD)
var oLD=_n('view')
_r(oLD,'class',109,e,s,gg)
var cMD=_n('view')
_r(cMD,'style',110,e,s,gg)
var oND=_o(111,e,s,gg)
_(cMD,oND)
_(oLD,cMD)
var lOD=_n('view')
var aPD=_o(112,e,s,gg)
_(lOD,aPD)
_(oLD,lOD)
_(oFD,oLD)
_(o2C,oFD)
var tQD=_n('view')
_r(tQD,'class',113,e,s,gg)
var eRD=_n('view')
_r(eRD,'class',114,e,s,gg)
var bSD=_n('view')
var oTD=_o(115,e,s,gg)
_(bSD,oTD)
_(eRD,bSD)
var xUD=_n('view')
_r(xUD,'style',116,e,s,gg)
var oVD=_o(117,e,s,gg)
_(xUD,oVD)
_(eRD,xUD)
_(tQD,eRD)
var fWD=_n('view')
_r(fWD,'class',118,e,s,gg)
var cXD=_n('view')
var hYD=_o(119,e,s,gg)
_(cXD,hYD)
_(fWD,cXD)
var oZD=_n('view')
_r(oZD,'style',120,e,s,gg)
var c1D=_o(121,e,s,gg)
_(oZD,c1D)
_(fWD,oZD)
_(tQD,fWD)
var o2D=_n('view')
_r(o2D,'class',122,e,s,gg)
var l3D=_n('view')
var a4D=_o(123,e,s,gg)
_(l3D,a4D)
_(o2D,l3D)
var t5D=_n('view')
_r(t5D,'style',124,e,s,gg)
var e6D=_o(125,e,s,gg)
_(t5D,e6D)
_(o2D,t5D)
_(tQD,o2D)
_(o2C,tQD)
var o4C=_v()
_(o2C,o4C)
if(_o(126,e,s,gg)){o4C.wxVkey=1
o4C.wxXCkey=1
var b7D=_n('view')
_r(b7D,'class',127,e,s,gg)
var o8D=_n('view')
_r(o8D,'class',128,e,s,gg)
var x9D=_n('view')
var o0D=_o(129,e,s,gg)
_(x9D,o0D)
_(o8D,x9D)
var fAE=_n('view')
_r(fAE,'style',130,e,s,gg)
var cBE=_o(131,e,s,gg)
_(fAE,cBE)
_(o8D,fAE)
_(b7D,o8D)
_(o4C,b7D)
}
var f5C=_v()
_(o2C,f5C)
if(_o(132,e,s,gg)){f5C.wxVkey=1
f5C.wxXCkey=1
var hCE=_n('view')
_r(hCE,'class',133,e,s,gg)
var oDE=_v()
_(hCE,oDE)
var cEE=function(lGE,oFE,aHE,gg){
var eJE=_m('view',['class',136,'data-index',1],[],lGE,oFE,gg)
var bKE=_n('view')
var oLE=_o(138,lGE,oFE,gg)
_(bKE,oLE)
_(eJE,bKE)
var xME=_n('view')
_r(xME,'style',139,lGE,oFE,gg)
var oNE=_o(140,lGE,oFE,gg)
_(xME,oNE)
_(eJE,xME)
_(aHE,eJE)
return aHE
}
oDE.wxXCkey=2
_2(134,cEE,e,s,gg,oDE,'item','index','')
_(f5C,hCE)
}
var fOE=_n('view')
_r(fOE,'class',141,e,s,gg)
var cPE=_n('view')
_r(cPE,'class',142,e,s,gg)
var hQE=_o(143,e,s,gg)
_(cPE,hQE)
_(fOE,cPE)
var oRE=_n('view')
_r(oRE,'class',144,e,s,gg)
var cSE=_o(145,e,s,gg)
_(oRE,cSE)
_(fOE,oRE)
_(o2C,fOE)
var oTE=_n('view')
_r(oTE,'class',146,e,s,gg)
var aVE=_n('view')
_r(aVE,'class',147,e,s,gg)
var tWE=_n('view')
_r(tWE,'class',148,e,s,gg)
var eXE=_v()
_(tWE,eXE)
if(_o(149,e,s,gg)){eXE.wxVkey=1
eXE.wxXCkey=1
var bYE=_n('text')
var oZE=_o(150,e,s,gg)
_(bYE,oZE)
_(eXE,bYE)
}
else{eXE.wxVkey=2
var x1E=_n('text')
var o2E=_o(151,e,s,gg)
_(x1E,o2E)
_(eXE,x1E)
}
_(aVE,tWE)
var f3E=_n('view')
_r(f3E,'class',152,e,s,gg)
_(aVE,f3E)
_(oTE,aVE)
var lUE=_v()
_(oTE,lUE)
if(_o(153,e,s,gg)){lUE.wxVkey=1
lUE.wxXCkey=1
var c4E=_n('view')
_r(c4E,'class',154,e,s,gg)
var h5E=_v()
_(c4E,h5E)
var o6E=_o(156,e,s,gg)
var c7E=_gd(x[4],o6E,e_,d_)
if(c7E){
var o8E=_1(155,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(155)
c7E(o8E,o8E,h5E,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(o6E,x[4],70,20)
_(lUE,c4E)
}
_(o2C,oTE)
var l9E=_n('view')
_r(l9E,'class',157,e,s,gg)
var a0E=_m('view',['bindtap',158,'class',1],[],e,s,gg)
var tAF=_n('view')
_r(tAF,'class',160,e,s,gg)
var eBF=_n('image')
_r(eBF,'src',161,e,s,gg)
_(tAF,eBF)
_(a0E,tAF)
var bCF=_n('view')
_r(bCF,'class',162,e,s,gg)
var oDF=_o(163,e,s,gg)
_(bCF,oDF)
_(a0E,bCF)
_(l9E,a0E)
var xEF=_v()
_(l9E,xEF)
var oFF=function(cHF,fGF,hIF,gg){
var cKF=_m('view',['bindtap',166,'class',1],[],cHF,fGF,gg)
var oLF=_n('view')
_r(oLF,'class',168,cHF,fGF,gg)
var lMF=_n('image')
_r(lMF,'src',169,cHF,fGF,gg)
_(oLF,lMF)
_(cKF,oLF)
var aNF=_n('view')
_r(aNF,'class',170,cHF,fGF,gg)
var tOF=_o(171,cHF,fGF,gg)
_(aNF,tOF)
_(cKF,aNF)
_(hIF,cKF)
return hIF
}
xEF.wxXCkey=2
_2(164,oFF,e,s,gg,xEF,'item','index','')
_(o2C,l9E)
var ePF=_n('view')
_r(ePF,'class',172,e,s,gg)
var bQF=_v()
_(ePF,bQF)
var oRF=_o(174,e,s,gg)
var xSF=_gd(x[4],oRF,e_,d_)
if(xSF){
var oTF=_1(173,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(173)
xSF(oTF,oTF,bQF,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(oRF,x[4],90,18)
_(o2C,ePF)
var fUF=_v()
_(o2C,fUF)
var cVF=_o(176,e,s,gg)
var hWF=_gd(x[4],cVF,e_,d_)
if(hWF){
var oXF=_1(175,e,s,gg) || {}
var cur_globalf=gg.f
gg.valuekey.push(175)
hWF(oXF,oXF,fUF,gg)
gg.valuekey.pop()
gg.f=cur_globalf
}
else _w(cVF,x[4],93,16)
_(r,o2C)
b1C.pop()
return r
}